### PR TITLE
Windows fix

### PR DESCRIPTION
**Pull request by vendethiel**

### CODE REVIEW

**Comment by vendethiel** [comment]
I just did that through github editor though, probably needs testing ...

**Comment by vendethiel** [comment]
@danielberndt ?

**Comment by vendethiel** [comment]
@jzimmek or @schafstelze ?

**Comment by vendethiel** [comment]
I guess there's a reason why it's called **patience** labs :-).

**Comment by knuton** [comment]
@vendethiel Made me laugh :wink: 

At this point I think it is clear that this is an unsupported project. It is no longer in use at Patience and there will be no "official" updates.

If it is still useful to you, fork it, maintain the fork, properly publish it to Sonatype, etc.

**Pull request closed without merging**
